### ISSUE TITLE
The handle is invalid

### ISSUE THREAD

**Issue by twoolworth** [dankeder/pg_dump_sample#1]
After building the application with Go I am unable to get the binary to produce a dump of the database being requested. From my best guess it's skipping over letting me provide a password and that's where the error message of "The handle is invalid" is coming from but not entirely sure.

The complete command I'm running is:
`C:\Users\Travis\gowork\bin\pg_dump_sample /m filter.yaml /h localhost /U postgres /f mydb_dump.sql mydb`

The output I receive is:
`Password for postgres:`
`Error: The handle is invalid.`

My filter.yaml file is very basic and I don't think the cause of the issue. It's contents are:

`tables:`
`  - table: Teams`

**Comment by dankeder** [comment]
Hi, thanks for the bugreport. The problem is indeed when reading the password from the terminal (it's trying to do it securely without echoing typed characters).

This commit *should* fix the problem: https://github.com/dankeder/pg_dump_sample/commit/5dd462f1cb439df4bd4a50f133af9d7e82ad48b3 (it's already in merged master). Unfortunately I can't test it on Windows because I don't use it, but go ahead and give it a try.

**Comment by twoolworth** [comment]
Thank you! After rebuilding the application with your new commit I was able to type a password now and successfully create a dump file.
